Update .gitignore
gmerveartar/JavaAppStudyRepo pull request #4
Opened 2023-12-11 16:24 UTC by gmerveartar

Maven and IntelliJ file extensions are added to gitignore

2023-12-12 23:10 UTC, ms2892 commented on .gitignore
> +.mvn/wrapper/maven-wrapper.jar
shouldn't there be a `*.class` as well?

2023-12-13 18:58 UTC, gmerveartar commented on .gitignore
> +.mvn/wrapper/maven-wrapper.jar
yep, I'll add those as well

2023-12-24 22:13 UTC, ms2892 approved these changes
Looks good to me. I love the addition of *.class in gitignore. It did help reduce the number of files significantly

2024-01-05 14:02 UTC, ms2892 approved these changes

2024-01-05 19:32 UTC, ms2892 requested changes

2024-01-05 19:32 UTC, ms2892 commented on Libraries/UtilLib/src/main/java/org/csystem/util/numeric/NumberUtil.java
> +            if (count == n)
This comparison doesn't work. You will have to change this line to 

```
if (count.compareTo(n)==0)
```

2024-01-06 16:34 UTC, ms2892 approved these changes
looks good to me

2024-01-06 16:37 UTC, merged